- hosts: all
  become: true
  tasks:
    - name: Update Repositories Index (Ubuntu)
      apt:
        update_cache: yes
        lock_timeout: 300
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - ./roles/common
